// Command gen-completions emits bash, zsh, or fish shell-completion
// scripts for mtroamd or mtroam. The single source of truth for what
// subcommands and flags exist is internal/completions/spec.go.
//
// Usage:
//
//	gen-completions -shell bash -binary mtroam > mtroam.bash
//	gen-completions -shell zsh  -binary mtroam > _mtroam
//	gen-completions -shell fish -binary mtroam > mtroam.fish
//
// `make completions` invokes this once per (shell, binary) pair and
// writes the output under dist/completions/.
package main

import (
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/AG-Studio-Apps/mtroamd/internal/completions"
)

func main() {
	shell := flag.String("shell", "", "completion shell: bash | zsh | fish")
	bin := flag.String("binary", "", "binary to generate completions for: mtroam | mtroamd")
	flag.Parse()

	var b completions.Binary
	switch *bin {
	case "mtroam":
		b = completions.Mtroam
	case "mtroamd":
		b = completions.Mtroamd
	default:
		fmt.Fprintf(os.Stderr, "gen-completions: -binary must be 'mtroam' or 'mtroamd' (got %q)\n", *bin)
		os.Exit(2)
	}

	var out string
	switch *shell {
	case "bash":
		out = emitBash(b)
	case "zsh":
		out = emitZsh(b)
	case "fish":
		out = emitFish(b)
	default:
		fmt.Fprintf(os.Stderr, "gen-completions: -shell must be 'bash', 'zsh', or 'fish' (got %q)\n", *shell)
		os.Exit(2)
	}
	fmt.Print(out)
}

// emitBash produces a bash completion script. The generated function
// gates on COMP_CWORD: position 1 is the subcommand, anything starting
// with `-` after that is a per-subcommand flag.
func emitBash(b completions.Binary) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s bash completion — generated by cmd/gen-completions; do not edit by hand\n", b.Name)
	fmt.Fprintf(&sb, "_%s() {\n", b.Name)
	sb.WriteString("    local cur prev sub\n")
	sb.WriteString("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
	sb.WriteString("    prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
	sb.WriteString("    sub=\"${COMP_WORDS[1]}\"\n")
	sb.WriteString("    if [[ $COMP_CWORD -eq 1 ]]; then\n")
	sb.WriteString("        COMPREPLY=( $(compgen -W \"")
	for i, s := range b.Subcommands {
		if i > 0 {
			sb.WriteString(" ")
		}
		sb.WriteString(s.Name)
	}
	sb.WriteString("\" -- \"$cur\") )\n")
	sb.WriteString("        return 0\n")
	sb.WriteString("    fi\n")
	sb.WriteString("    if [[ \"$cur\" == -* ]]; then\n")
	sb.WriteString("        case \"$sub\" in\n")
	for _, s := range b.Subcommands {
		if len(s.Flags) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "            %s) COMPREPLY=( $(compgen -W \"", s.Name)
		for i, f := range s.Flags {
			if i > 0 {
				sb.WriteString(" ")
			}
			sb.WriteString(f.Long)
		}
		sb.WriteString(" --help\" -- \"$cur\") );;\n")
	}
	sb.WriteString("        esac\n")
	sb.WriteString("    fi\n")
	sb.WriteString("}\n")
	fmt.Fprintf(&sb, "complete -F _%s %s\n", b.Name, b.Name)
	return sb.String()
}

// emitZsh produces a zsh completion function. Uses compsys
// `_arguments` shape; users source it via fpath + autoload.
func emitZsh(b completions.Binary) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "#compdef %s\n", b.Name)
	fmt.Fprintf(&sb, "# %s zsh completion — generated by cmd/gen-completions; do not edit by hand\n", b.Name)
	fmt.Fprintf(&sb, "_%s() {\n", b.Name)
	sb.WriteString("    local -a commands\n")
	sb.WriteString("    commands=(\n")
	for _, s := range b.Subcommands {
		// _describe wants 'name:help'. Escape any colons and any
		// embedded single-quotes — the latter would otherwise close
		// the surrounding '...' string and break the script.
		help := strings.ReplaceAll(s.Help, ":", "\\:")
		help = escapeZsh(help)
		fmt.Fprintf(&sb, "        '%s:%s'\n", s.Name, help)
	}
	sb.WriteString("    )\n")
	sb.WriteString("    _arguments -C \\\n")
	sb.WriteString("        '1: :->cmd' \\\n")
	sb.WriteString("        '*::arg:->args'\n")
	sb.WriteString("    case $state in\n")
	fmt.Fprintf(&sb, "        cmd) _describe -t commands '%s subcommand' commands ;;\n", b.Name)
	sb.WriteString("        args)\n")
	sb.WriteString("            case $words[1] in\n")
	for _, s := range b.Subcommands {
		if len(s.Flags) == 0 {
			continue
		}
		fmt.Fprintf(&sb, "                %s) _arguments \\\n", s.Name)
		for i, f := range s.Flags {
			help := escapeZsh(f.Help)
			sep := " \\"
			if i == len(s.Flags)-1 {
				sep = ""
			}
			fmt.Fprintf(&sb, "                    '%s[%s]'%s\n", f.Long, help, sep)
		}
		sb.WriteString("                ;;\n")
	}
	sb.WriteString("            esac\n")
	sb.WriteString("        ;;\n")
	sb.WriteString("    esac\n")
	sb.WriteString("}\n")
	fmt.Fprintf(&sb, "_%s \"$@\"\n", b.Name)
	return sb.String()
}

// emitFish produces a fish completion script. Each line is a single
// `complete -c <bin> ...` rule.
func emitFish(b completions.Binary) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s fish completion — generated by cmd/gen-completions; do not edit by hand\n", b.Name)
	for _, s := range b.Subcommands {
		help := escapeFish(s.Help)
		fmt.Fprintf(&sb, "complete -c %s -f -n '__fish_use_subcommand' -a '%s' -d '%s'\n",
			b.Name, s.Name, help)
	}
	for _, s := range b.Subcommands {
		if len(s.Flags) == 0 {
			continue
		}
		for _, f := range s.Flags {
			long := strings.TrimPrefix(f.Long, "--")
			help := escapeFish(f.Help)
			fmt.Fprintf(&sb,
				"complete -c %s -n '__fish_seen_subcommand_from %s' -l %s -d '%s'\n",
				b.Name, s.Name, long, help)
		}
	}
	return sb.String()
}

// escapeFish sanitises a help string for embedding inside the
// single-quoted argument of `complete -d '...'`. Fish treats single
// quotes literally inside a `'...'` token, so we just escape backslash
// and single quote.
func escapeFish(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "'", "\\'")
	return s
}

// escapeZsh handles single quotes inside a zsh single-quoted string.
// Inside '...' zsh treats every character literally, including
// backslash, so the standard trick is to close the string, emit a
// quoted single-quote, and reopen: ' → '\''.
//
// We also do not escape brackets here — _arguments expects '...[...]'
// to delimit the description, and our help text never contains
// brackets.
func escapeZsh(s string) string {
	return strings.ReplaceAll(s, "'", `'\''`)
}
